controllers_health:
    resource:
        path: ../src/Health/Controller/
        namespace: App\Health\Controller
    type: attribute

controllers_auth:
    resource:
        path: ../src/Authentication/Controller/
        namespace: App\Authentication\Controller
    type: attribute
