services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
      args:
        ENABLE_XDEBUG: "1"
    container_name: backend
    working_dir: /var/www/backend
    environment:
      APP_ENV: dev
      XDEBUG_MODE: "develop,debug"
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003"
    volumes:
      - ./backend:/var/www/backend:delegated
      - ./docker/backend/.env.local:/var/www/backend/.env.local:ro
      - ./docker/backend/dev.ini:/usr/locale/etc/php/conf.d/dev.ini:ro
    tmpfs:
      - /var/www/backend/var/cache

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app:delegated

  nginx:
    image: nginx:1.27-alpine
    container_name: web
    depends_on:
      - backend
      - frontend
    ports:
      - "8081:80"
    volumes:
      - ./backend:/var/www/backend:ro
      - ./frontend/dist/frontend/browser:/usr/share/nginx/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sp_dev
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - "./locale/mysql:/var/lib/mysql"
    depends_on:
      - backend
      
